carriermappings:
  HashMap:
    MSC:
      - carrierid: carrierid
        accountid: accountid
        groupid: groupid
      - carrierid: carrierid
        accountid: accountid
        groupid: groupid
      - carrierid: carrierid
        accountid: accountid
        groupid: groupid