spring:
  application:
    name: login-api
  jackson:
    default-property-inclusion: NON_NULL
   
prop:
  user-validation-v3-uri: https://gateway-stage.optum.com/api/stage/cel/rx/commoncapability/v2.0/validatev3/login.json
  ecs-membersearch-v2-uri: https://orxapi-stage.optum.com/api/stage/cel/orxesb/membersearch/v2
  ecs-consumingAppId: POR2
  ecs-consumerAppType: IA
  
  
  stargate:
    url: https://gateway-stage.optum.com/auth/oauth2/cached/token
    grant_type: client_credentials
    client_id: wSj4Er9Jv0CTDnDzPdRVYdrJpywv7Prx
    client_secret: 03r0xRorJEcMLrG8b5rrDPwsi281Z7IV
    erroe : name
    
    
  orxapi:
      url: https://orxapi-stage.optum.com/auth/oauth2/cached/token
      grant_type: client_credentials
      client_id: wSj4Er9Jv0CTDnDzPdRVYdrJpywv7Prx
      client_secret: 03r0xRorJEcMLrG8b5rrDPwsi281Z7IV
    
azure:
  application-insights:
    instrumentation-key: 8a9eb7f2-d8ac-4337-9685-16b1715ce21c
    
#carriermappings:
#  HashMap:
#    CVS:
#      - carrierid: carrierid
#        accountid: accountid
#        groupid: groupid
#      - carrierid: carrierid
#        accountid: accountid
#        groupid: groupid
#      - carrierid: carrierid
#        accountid: accountid
#        groupid: groupid
#    WALMART:
#      - carrierid: carrierid
#        accountid: accountid
#        groupid: groupid
#      - carrierid: carrierid
#        accountid: accountid
#        groupid: groupid
#      - carrierid: carrierid
#        accountid: accountid
#        groupid: groupid
#      - carrierid: carrierid
#        accountid: accountid
#        groupid: groupid

