carriermappings:
  HashMap:
    WALMART:
      - carrierid: WMARTRX
        accountid: 
        groupid: 
      - carrierid: WMARTRX2
        accountid: 
        groupid: 
      - carrierid: WMARTRX2
        accountid: 
        groupid: 
