carriermappings:
  HashMap:
    MSC:
      - carrierid: PDPIND
        accountid: 
        groupid: 
      - carrierid: UHCNI2500
        accountid: 
        groupid: 
      - carrierid: PSI2500
        accountid: 
        groupid: 
      - carrierid: PSI1450
        accountid: 
        groupid: 
      - carrierid: UHC0005XX
        accountid: 
        groupid: 
      - carrierid: UHCACIS01
        accountid: 
        groupid: 
      - carrierid: BKC1
        accountid: 
        groupid: 
      - carrierid: PSI1150
        accountid: 
        groupid: 
      - carrierid: PDPING
        accountid: 
        groupid: 
      - carrierid: UHCACCNT1
        accountid: 
        groupid: 
      - carrierid: PSI100U
        accountid: 
        groupid: 
